### ISSUE TITLE
Data credits in app

### ISSUE THREAD

**Issue by ErlendEllingsen** [vanillastatus/VanillaStatusApp#24]
Love the app and the results. Just make sure to display a credit to ElysiumStatus.com in the app or wherever the data is being used! 👍

**Comment by emmoistner** [comment]
@ErlendEllingsen Thinking something like a splash screen. Maybe a little more branded, but general idea.

<img src='https://cloud.githubusercontent.com/assets/5419727/22236277/a6fd3fd4-e1d2-11e6-9fca-3d0aa5d09bd1.png' height=300 />
